# Generated by Django 3.2.11 on 2022-01-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=50, verbose_name='Notification heading')),
                ('message', models.CharField(blank=True, max_length=250, null=True, verbose_name='Notification message')),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('DANGER', 'Danger'), ('WARNING', 'Warning'), ('INFO', 'Info')], max_length=10, verbose_name='Notification Status')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
