# Generated by Django 3.2.11 on 2022-01-09 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_auto_20220108_1420'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.AddField(
            model_name='notification',
            name='mark_read',
            field=models.BooleanField(default=False, verbose_name='Mark as Read'),
        ),
    ]
